collections_config:
  blog:
    schemas:
      default:
        path: schemas/blog.md

data_config:
  authors: true

paths:
  static: static/uploads
  uploads: static/uploads

_inputs:
  menu:
    hidden: true
  layout:
    hidden: true
  featured_image:
    type: image
    comment: Set your featured image. Featured images are used as your SEO preview image when shared on social media or when your page is found in organic search results.
  hero.image_url:
    type: image
    comment: This is the main image used at the top of every page.
    options:
      accepts_mime_types:
        - image/jpeg
  hero.mobile_image_url:
    type: image
    comment: This is an optional mobile version of the main image used at the top of every page.
    options:
      accepts_mime_types:
        - image/jpeg
  headshot:
    type: image
    options:
      accepts_mime_types:
        - image/jpeg
  image_url:
    type: image
    comment: Upload a .jpg image. Make sure to check the documentation for image handling best practices before adding images to the website.
    options:
      accepts_mime_types:
        - image/jpeg
  icon:
    type: image
    options:
      accepts_mime_types:
        - image/jpeg
        - image/svg+xml
  heading:
    type: text
  time:
    type: text
  url:
    type: text
    comment: Set a custom URL for your page. ex. /our-team/first-m-last/
  video:
    type: text
    comment: Please reach out to Insight Creative, Inc. if you need help changing a video.
  background_color:
    type: select
    comment: Choose between "white" or "gray" as a background color
    options:
      values:
        - white
        - gray
  body:
    type: markdown
  answer:
    type: markdown
  service_points:
    type: markdown
  button.button_url:
    type: url
  hero.button_url:
    type: url
  author:
    type: select
    options:
      values: data.authors
      value_key: title
