_inputs:
  featured_image:
    type: file
    comment: Set your featured image. Featured images are used as your SEO preview image when shared on social media or when your page is found in organic search results. The featured image is also used as the featured image on blog posts.
    options:
      uploads_dir: /static/uploads/
  url:
    type: text
    comment: Set a custom URL for your page. ex. /our-team/first-m-last/